### ISSUE TITLE
OpenCV and Tensorflow on Toybrick RK3399Pro Board

### ISSUE THREAD

**Issue by anferico** [rockchip-toybrick/RKNPUTool#5]
I got a Toybrick RK3399Pro Board (whose architecture is aarch64) where I want to install the RKNPU Toolkit. Along with the wheel package (rknn_toolkit-0.9.9-cp36-cp36m-linux_aarch64.whl), I found another file containing python dependencies for such toolkit, namely "requirements-cpu.txt". Two of such dependencies are:

1. opencv-python>=3.4.3.18
2. tensorflow>=1.11.0

However, if I run: 
`pip3 install opencv-python>=3.4.3.18`
I get this error: 
```
ERROR: Could not find a version that satisfies the requirement opencv-python>=3.4.3.18 (from -r requirements-cpu.txt (line 12)) (from versions: none)                                                         
ERROR: No matching distribution found for opencv-python>=3.4.3.18 (from -r requirements-cpu.txt (line 12))
```
while if I run: 
`pip3 install tensorflow>=1.11.0` I get:
```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```
Removing version specifications (thus running `pip3 install opencv-python` and `pip3 install tensorflow`) does not help, as I'm still unable to install neither OpenCV nor Tensorflow.

**Comment by Iamanorange** [comment]
`requirements-cpu.txt` is for your developing system (a x86 computer without GPU). You don't need it on the board.

BTW RK released rknn_tool 1.0. Better to upgrade.
